###
POST http://localhost:4000/user/signup
Content-Type: application/json

{
    "username": "newTest",
    "email": "testtest@gmail.com",
    "password": "Testtest1$"
}

###
GET http://localhost:4000/user/
Content-Type: application/json